
package mathsservice;

/**
 *
 * @author Jamie
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Supportpanel = new javax.swing.JPanel();
        Mathsbtn = new javax.swing.JToggleButton();
        Infobtn = new javax.swing.JToggleButton();
        Questionbtn = new javax.swing.JToggleButton();
        Contactbtn = new javax.swing.JToggleButton();
        Disabilitybtn = new javax.swing.JToggleButton();
        Titlelb = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 725));
        getContentPane().setLayout(null);

        Supportpanel.setOpaque(false);

        Mathsbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Mathsbtn.setText("Maths Support");
        Mathsbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Mathsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mathsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsbtnActionPerformed(evt);
            }
        });

        Infobtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Infobtn.setText("Info");
        Infobtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Infobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Infobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfobtnActionPerformed(evt);
            }
        });

        Questionbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Questionbtn.setText("Ask Us Anything");
        Questionbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Questionbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Questionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionbtnActionPerformed(evt);
            }
        });

        Contactbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Contactbtn.setText("Contact");
        Contactbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Contactbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contactbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactbtnActionPerformed(evt);
            }
        });

        Disabilitybtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Disabilitybtn.setText("Disability Support");
        Disabilitybtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Disabilitybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Disabilitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilitybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SupportpanelLayout = new javax.swing.GroupLayout(Supportpanel);
        Supportpanel.setLayout(SupportpanelLayout);
        SupportpanelLayout.setHorizontalGroup(
            SupportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contactbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Infobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SupportpanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Questionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupportpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SupportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Disabilitybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mathsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        SupportpanelLayout.setVerticalGroup(
            SupportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportpanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(Mathsbtn)
                .addGap(33, 33, 33)
                .addComponent(Disabilitybtn)
                .addGap(164, 164, 164)
                .addComponent(Questionbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(SupportpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contactbtn)
                    .addComponent(Infobtn))
                .addContainerGap())
        );

        getContentPane().add(Supportpanel);
        Supportpanel.setBounds(0, 100, 460, 580);

        Titlelb.setFont(new java.awt.Font("Batang", 3, 24)); // NOI18N
        Titlelb.setText("National College Of Ireland ");
        getContentPane().add(Titlelb);
        Titlelb.setBounds(50, 40, 480, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsservice/Images/SupportService.gif"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 460, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MathsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsbtnActionPerformed
        dispose();
        MathsGUIpg1 MGUI = new MathsGUIpg1();
        MGUI.setVisible(true);
        
    }//GEN-LAST:event_MathsbtnActionPerformed

    private void InfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfobtnActionPerformed
        dispose();
        InfoGUI IGUI = new InfoGUI();
        IGUI.setVisible(true);
    }//GEN-LAST:event_InfobtnActionPerformed

    private void ContactbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactbtnActionPerformed
        dispose();
        ContactGUI CGUI = new ContactGUI();
        CGUI.setVisible(true);
    }//GEN-LAST:event_ContactbtnActionPerformed

    private void QuestionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionbtnActionPerformed
        dispose();
        QuestionGUI QGUI = new QuestionGUI();
        QGUI.setVisible(true);
    }//GEN-LAST:event_QuestionbtnActionPerformed

    private void DisabilitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisabilitybtnActionPerformed
        dispose();
        DisGUI1 DGUI = new DisGUI1();
        DGUI.setVisible(true);
    }//GEN-LAST:event_DisabilitybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JToggleButton Contactbtn;
    private javax.swing.JToggleButton Disabilitybtn;
    private javax.swing.JToggleButton Infobtn;
    private javax.swing.JToggleButton Mathsbtn;
    private javax.swing.JToggleButton Questionbtn;
    private javax.swing.JPanel Supportpanel;
    private javax.swing.JLabel Titlelb;
    // End of variables declaration//GEN-END:variables
}
