/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsservice;
//The Calculator was studyed from youtube videos and Java Books it is not all my code 
/**
 *
 * @author Jamie
 */
public class MathsGUIpg1 extends javax.swing.JFrame {

     //Variables
    double plusminus;
    double firstDouble;
    double secondDouble;
    double totalDouble;
    //to check for button clicks
    int plusClick;
    int minusClick;
    int multiplyClick;
    int divideClick;
    
    public MathsGUIpg1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Titlelb = new javax.swing.JLabel();
        Aboutlb = new javax.swing.JLabel();
        Contactlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nextbtn = new javax.swing.JButton();
        Info = new javax.swing.JScrollPane();
        InfoFeild = new javax.swing.JTextArea();
        Contact = new javax.swing.JScrollPane();
        Contactfeild = new javax.swing.JTextArea();
        Cal = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        One = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        posneg = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        decminal = new javax.swing.JButton();
        Equals = new javax.swing.JButton();
        Quick = new javax.swing.JPanel();
        Gamebtn = new javax.swing.JButton();
        Appoimnetbtn = new javax.swing.JButton();
        Calucatorbtn = new javax.swing.JButton();
        Formulas = new javax.swing.JButton();
        hintsbtn = new javax.swing.JButton();
        Qtitellb = new javax.swing.JLabel();
        Events = new javax.swing.JScrollPane();
        Eventsfeild = new javax.swing.JTextArea();
        Homebtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 725));
        getContentPane().setLayout(null);

        Titlelb.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Titlelb.setText("Maths Support Page");
        getContentPane().add(Titlelb);
        Titlelb.setBounds(140, 10, 200, 22);

        Aboutlb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Aboutlb.setText("About and Events");
        getContentPane().add(Aboutlb);
        Aboutlb.setBounds(90, 50, 140, 17);

        Contactlb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Contactlb.setText("Contact");
        getContentPane().add(Contactlb);
        Contactlb.setBounds(50, 380, 80, 17);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("Students Helpful Calculator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 380, 200, 17);

        Nextbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Nextbtn.setText("Next");
        Nextbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nextbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Nextbtn);
        Nextbtn.setBounds(350, 10, 100, 21);

        Info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        InfoFeild.setEditable(false);
        InfoFeild.setColumns(20);
        InfoFeild.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        InfoFeild.setRows(5);
        InfoFeild.setText("The Maths Support Service is one of a number of \nservices offered by the NCI Student Support \nservice. The service provides an informal \nenvironment for students who are experiencing \ndifficulties or wish to improve their understanding \nof and confidence in mathematical concepts.\n\nThe maths support service is running dedicated \nprgramme workshops. They are a great place to \nask questions and get advice.");
        InfoFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        Info.setViewportView(InfoFeild);

        getContentPane().add(Info);
        Info.setBounds(10, 70, 300, 160);

        Contact.setHorizontalScrollBar(null);

        Contactfeild.setEditable(false);
        Contactfeild.setColumns(10);
        Contactfeild.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Contactfeild.setRows(5);
        Contactfeild.setText("\nMaths Support:\n\nJohnathan Lambert\n\nEmail:\njohnathan.lambert\n@ncril.ie\n\nPhone:\n(01)4498650");
        Contactfeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Contactfeild.setMinimumSize(new java.awt.Dimension(30, 30));
        Contact.setViewportView(Contactfeild);

        getContentPane().add(Contact);
        Contact.setBounds(10, 400, 150, 250);

        Cal.setBackground(new java.awt.Color(204, 204, 204));
        Cal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Cal.setForeground(new java.awt.Color(204, 204, 204));
        Cal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        display.setEditable(false);
        display.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        One.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        multiply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        multiply.setText("x");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        posneg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        posneg.setText("+/-");
        posneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posnegActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        decminal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        decminal.setText(".");
        decminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decminalActionPerformed(evt);
            }
        });

        Equals.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Equals.setText("=");
        Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalLayout = new javax.swing.GroupLayout(Cal);
        Cal.setLayout(CalLayout);
        CalLayout.setHorizontalGroup(
            CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display)
                    .addGroup(CalLayout.createSequentialGroup()
                        .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalLayout.createSequentialGroup()
                        .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CalLayout.createSequentialGroup()
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decminal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalLayout.createSequentialGroup()
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalLayout.createSequentialGroup()
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalLayout.createSequentialGroup()
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(posneg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        CalLayout.setVerticalGroup(
            CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posneg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decminal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(Cal);
        Cal.setBounds(170, 400, 280, 250);

        Quick.setBackground(new java.awt.Color(204, 204, 204));
        Quick.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Gamebtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Gamebtn.setText("Test Yourself");
        Gamebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Gamebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamebtnActionPerformed(evt);
            }
        });

        Appoimnetbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Appoimnetbtn.setText("Appointment");
        Appoimnetbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Appoimnetbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Appoimnetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppoimnetbtnActionPerformed(evt);
            }
        });

        Calucatorbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Calucatorbtn.setText("Calculator");
        Calucatorbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Calucatorbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calucatorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalucatorbtnActionPerformed(evt);
            }
        });

        Formulas.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Formulas.setText("Helpful Site's");
        Formulas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Formulas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Formulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormulasActionPerformed(evt);
            }
        });

        hintsbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        hintsbtn.setText("Hints");
        hintsbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hintsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hintsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuickLayout = new javax.swing.GroupLayout(Quick);
        Quick.setLayout(QuickLayout);
        QuickLayout.setHorizontalGroup(
            QuickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuickLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Appoimnetbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(Gamebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(Calucatorbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Formulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hintsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        QuickLayout.setVerticalGroup(
            QuickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuickLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Appoimnetbtn)
                .addGap(31, 31, 31)
                .addComponent(Calucatorbtn)
                .addGap(34, 34, 34)
                .addComponent(Gamebtn)
                .addGap(37, 37, 37)
                .addComponent(Formulas)
                .addGap(37, 37, 37)
                .addComponent(hintsbtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(Quick);
        Quick.setBounds(320, 70, 130, 300);

        Qtitellb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Qtitellb.setText("Quick Menu ");
        getContentPane().add(Qtitellb);
        Qtitellb.setBounds(340, 50, 100, 17);

        Eventsfeild.setEditable(false);
        Eventsfeild.setColumns(20);
        Eventsfeild.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Eventsfeild.setRows(5);
        Eventsfeild.setText("Support Sessions : \n\nComputer Architecture\n\n1.Thursday 3.30pm - 4.30pm Room 3.08\n2.Friday 10.00am - 11.00am Room 1.11");
        Eventsfeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Events.setViewportView(Eventsfeild);

        getContentPane().add(Events);
        Events.setBounds(10, 240, 300, 130);

        Homebtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Homebtn.setText("Home");
        Homebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Homebtn);
        Homebtn.setBounds(10, 10, 100, 21);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsservice/Images/Maths Background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 460, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        firstDouble=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        plusClick=1;
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        firstDouble=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        minusClick=1;
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        firstDouble=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        multiplyClick=1;
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        firstDouble=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        divideClick=1;
    }//GEN-LAST:event_divideActionPerformed

    private void posnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posnegActionPerformed
        plusminus=(Double.parseDouble(String.valueOf(display.getText())));
        plusminus=plusminus*(-1);
        display.setText(String.valueOf(plusminus));
    }//GEN-LAST:event_posnegActionPerformed

    private void EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsActionPerformed
       secondDouble=(Double.parseDouble(String.valueOf(display.getText())));
        if(plusClick>0){
            totalDouble=firstDouble+secondDouble;
            display.setText((String.valueOf(totalDouble)));
            firstDouble=0;
            secondDouble=0;
            plusClick=0;
        
        }
        if(minusClick>0){
            totalDouble=firstDouble-secondDouble;
            display.setText((String.valueOf(totalDouble)));
            firstDouble=0;
            secondDouble=0;
            minusClick=0;
        
        }
        if(multiplyClick>0){
            totalDouble=firstDouble*secondDouble;
            display.setText((String.valueOf(totalDouble)));
            firstDouble=0;
            secondDouble=0;
            multiplyClick=0;
        
        }
        if(divideClick>0){
            totalDouble=firstDouble/secondDouble;
            display.setText((String.valueOf(totalDouble)));
            firstDouble=0;
            secondDouble=0;
            divideClick=0;
        
        }
    }//GEN-LAST:event_EqualsActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        display.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        display.setText(display.getText()+One.getText());
    }//GEN-LAST:event_OneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        display.setText(display.getText()+two.getText());
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        display.setText(display.getText()+three.getText());
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        display.setText(display.getText()+four.getText());
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        display.setText(display.getText()+five.getText());
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        display.setText(display.getText()+six.getText());
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        display.setText(display.getText()+seven.getText());
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        display.setText(display.getText()+eight.getText());
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        display.setText(display.getText()+nine.getText());
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        display.setText(display.getText()+zero.getText());
    }//GEN-LAST:event_zeroActionPerformed

    private void decminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decminalActionPerformed
        display.setText(display.getText()+decminal.getText());
    }//GEN-LAST:event_decminalActionPerformed

    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
        dispose();
        MathsGUIpg2 MGUI = new MathsGUIpg2();
        MGUI.setVisible(true);
    }//GEN-LAST:event_NextbtnActionPerformed

    private void AppoimnetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppoimnetbtnActionPerformed
        dispose();
        MathsGUIpg2 MGUI = new MathsGUIpg2();
        MGUI.setVisible(true);
    }//GEN-LAST:event_AppoimnetbtnActionPerformed

    private void CalucatorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalucatorbtnActionPerformed
        dispose();
        MathsGUIpg1 MGUI = new MathsGUIpg1();
        MGUI.setVisible(true);
    }//GEN-LAST:event_CalucatorbtnActionPerformed

    private void hintsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintsbtnActionPerformed
        dispose();
        MathsGUIpg2 MGUI = new MathsGUIpg2();
        MGUI.setVisible(true);
    }//GEN-LAST:event_hintsbtnActionPerformed

    private void GamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamebtnActionPerformed
        dispose();
        MathsGUIpg3 MGUI = new MathsGUIpg3();
        MGUI.setVisible(true);
    }//GEN-LAST:event_GamebtnActionPerformed

    private void FormulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormulasActionPerformed
        dispose();
        MathsGUIpg3 MGUI = new MathsGUIpg3();
        MGUI.setVisible(true);
    }//GEN-LAST:event_FormulasActionPerformed

    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
        dispose();
        Homepage HGUI = new Homepage();
        HGUI.setVisible(true);
    }//GEN-LAST:event_HomebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsGUIpg1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutlb;
    private javax.swing.JButton Appoimnetbtn;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Cal;
    private javax.swing.JButton Calucatorbtn;
    private javax.swing.JScrollPane Contact;
    private javax.swing.JTextArea Contactfeild;
    private javax.swing.JLabel Contactlb;
    private javax.swing.JButton Equals;
    private javax.swing.JScrollPane Events;
    private javax.swing.JTextArea Eventsfeild;
    private javax.swing.JButton Formulas;
    private javax.swing.JButton Gamebtn;
    private javax.swing.JButton Homebtn;
    private javax.swing.JScrollPane Info;
    private javax.swing.JTextArea InfoFeild;
    private javax.swing.JButton Nextbtn;
    private javax.swing.JButton One;
    private javax.swing.JLabel Qtitellb;
    private javax.swing.JPanel Quick;
    private javax.swing.JLabel Titlelb;
    private javax.swing.JButton clear;
    private javax.swing.JButton decminal;
    private javax.swing.JTextField display;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton hintsbtn;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton plus;
    private javax.swing.JButton posneg;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
