
package mathsservice;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamie
 */
public class MathsGUIpg3 extends javax.swing.JFrame {

public static String Question;
public static String Question2;
public static String Question3;
public static String Question4;
public static String Question5;

int Counter = 0;

    public MathsGUIpg3() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelb = new javax.swing.JLabel();
        Testlb = new javax.swing.JLabel();
        Forlb = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        testpanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        Mathstitle = new javax.swing.JLabel();
        setbtn = new javax.swing.JButton();
        logicbtn = new javax.swing.JButton();
        relationsbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Mathstitle1 = new javax.swing.JLabel();
        Numbers = new javax.swing.JButton();
        Morenumbers = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        text3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        Sites = new javax.swing.JScrollPane();
        Sitestf = new javax.swing.JTextArea();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 725));
        getContentPane().setLayout(null);

        titlelb.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titlelb.setText("Maths Support Page");
        getContentPane().add(titlelb);
        titlelb.setBounds(140, 10, 200, 22);

        Testlb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Testlb.setText("Test Yourself Below");
        getContentPane().add(Testlb);
        Testlb.setBounds(160, 50, 170, 17);

        Forlb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Forlb.setText("Helpful Site's");
        getContentPane().add(Forlb);
        Forlb.setBounds(180, 360, 140, 17);

        Back.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(10, 10, 100, 21);

        testpanel.setBackground(new java.awt.Color(204, 204, 204));
        testpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        testpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        text.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        text.setText("Click on one of the buttons below to begin your Test");

        text2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        text2.setText("If you want try the Random Quiz it can ask you anything ");

        Mathstitle.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Mathstitle.setText("Introduction to Maths ");

        setbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        setbtn.setText("Sets");
        setbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        setbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setbtnActionPerformed(evt);
            }
        });

        logicbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        logicbtn.setText("Logic");
        logicbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        logicbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicbtnActionPerformed(evt);
            }
        });

        relationsbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        relationsbtn.setText("Relations");
        relationsbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        relationsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationsbtnActionPerformed(evt);
            }
        });

        Mathstitle1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Mathstitle1.setText("Computer Architecture");

        Numbers.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Numbers.setText("Numbers");
        Numbers.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbersActionPerformed(evt);
            }
        });

        Morenumbers.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Morenumbers.setText("More Numbers");
        Morenumbers.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Morenumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorenumbersActionPerformed(evt);
            }
        });

        Random.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Random.setText("Random");
        Random.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        text3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        text3.setText("It will be multiple choice you will have to enter A,B,C OR D to move on ");

        javax.swing.GroupLayout testpanelLayout = new javax.swing.GroupLayout(testpanel);
        testpanel.setLayout(testpanelLayout);
        testpanelLayout.setHorizontalGroup(
            testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testpanelLayout.createSequentialGroup()
                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testpanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(testpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(testpanelLayout.createSequentialGroup()
                        .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(testpanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(Numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Morenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(testpanelLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(Random, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(testpanelLayout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(testpanelLayout.createSequentialGroup()
                                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(setbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(testpanelLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(Mathstitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(testpanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(testpanelLayout.createSequentialGroup()
                                                .addComponent(Mathstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(testpanelLayout.createSequentialGroup()
                                                .addComponent(logicbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(relationsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        testpanelLayout.setVerticalGroup(
            testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testpanelLayout.createSequentialGroup()
                .addComponent(text)
                .addGap(1, 1, 1)
                .addComponent(text3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mathstitle)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logicbtn)
                        .addComponent(relationsbtn))
                    .addComponent(setbtn))
                .addGap(18, 18, 18)
                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mathstitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(testpanelLayout.createSequentialGroup()
                        .addGroup(testpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Numbers)
                            .addComponent(Morenumbers))
                        .addGap(26, 26, 26)
                        .addComponent(text2))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Random)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(testpanel);
        testpanel.setBounds(10, 70, 440, 280);

        Sitestf.setEditable(false);
        Sitestf.setColumns(20);
        Sitestf.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Sitestf.setRows(5);
        Sitestf.setText("For more information on Maths Support or any of the other services go to :\n\nwww.ncirl.ie\n\nThere are also videos on a number of Computer Acrh topics on youtube \nthat will help you with such things as number conversions or Logic \ndesign.\n\nwww.youtube.com\n\nIf you have any questions please to not forget the contact us direcltly\nor Johnathan Lambert head of Maths Support ");
        Sitestf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Sites.setViewportView(Sitestf);

        getContentPane().add(Sites);
        Sites.setBounds(10, 380, 440, 270);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsservice/Images/Maths Background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 470, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        MathsGUIpg2 MGUI = new MathsGUIpg2();
        MGUI.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void setbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setbtnActionPerformed
        //The test system makes use of switch which I study from youtube and java websites
        //The Questions used in the quiz are taken from the moodle quiz's to help better prepare students for their type
        //Questions for Sets
        Question  = JOptionPane.showInputDialog(null, "1. Which of the following are true\nA. {1,2,3,4,5}\nB. 0 a^^ N\nC. {-2,-1,0,1,2}\nD. 0 a^^R\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Given A={1,2} and B={b,d,e}, What is A X B ?\nA. {(b,1), (d,1), (e,1), (2,b), (2,d), (2,e)}\nB. {(1,b), (1,d), (e,1), (2,b), (2,d), (e,2)}\nC. {(1,b), (1,d), (1,e), (2,b), (2,d), (2,e)}\nD. {(1,b), (1,d), (1,e), (b,2), (d,2), (e,2)}\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. List the elements of the setP(A n B) given A={1,2} and B={2,3}\nA. {{},{2}}\nB. 0 a^^ N\nC. {-2,-1,0,1,2}\nD. 0 a^^R\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4. How many elements will the P(A) have given A={1,2,3,4,5}?\nA. 6\nB. 14\nC. 44\nD. 32\nAnswer: ");
        char Q4 = Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question5  = JOptionPane.showInputDialog(null, "5. Give the cardinality of the following set {}\nA. 2\nB. 0\nC. 10\nD. 1\nAnswer: ");
        char Q5 = Question5.charAt(0);
        switch (Q5)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
    
       JOptionPane.showMessageDialog(null,100 * Counter/5 + "% is what you got in Sets");
    }//GEN-LAST:event_setbtnActionPerformed

    private void logicbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicbtnActionPerformed
        //Questions for Logic 
        Question  = JOptionPane.showInputDialog(null, "1. If P is False and Q is False then P V Q is\nA. True\nB. False\nC. Both\nD. None\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Is the statement P^(Q v T)\nA. True\nB. False\nC. None\nD. Both\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. If P is False and Q is True then P^Q is \nA. True\nB. None\nC. False\nD. Both\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4.  Is the staement (P^(Q^T)))\nA. False\nB. Both\nC. True\nD. None\nAnswer: ");
        char Q4 = Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question5  = JOptionPane.showInputDialog(null, "5. Given the negation of predicate ~P(x):x>8, which of the following is the predicate of P(x)\nA. x=9\nB. x>18\nC. x=0\nD. x<=8\nAnswer: ");
        char Q5 = Question5.charAt(0);
        switch (Q5)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
    
       JOptionPane.showMessageDialog(null,100 * Counter/5 + "% is what you got in logic ");
    }//GEN-LAST:event_logicbtnActionPerformed

    private void relationsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationsbtnActionPerformed
        //Questions for Relations 
        Question  = JOptionPane.showInputDialog(null, "1. If P is False and Q is False then P V Q is\nA. True\nB. False\nC. Both\nD. None\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Is the statement P^(Q v T)\nA. True\nB. False\nC. None\nD. Both\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. If P is False and Q is True then P^Q is \nA. True\nB. None\nC. False\nD. Both\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4.  Is the staement (P^(Q^T)))\nA. False\nB. Both\nC. True\nD. None\nAnswer: ");
        char Q4 = Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question5  = JOptionPane.showInputDialog(null, "5. Given the negation of predicate ~P(x):x>8, which of the following is the predicate of P(x)\nA. x=9\nB. x>18\nC. x=0\nD. x<=8\nAnswer: ");
        char Q5 = Question5.charAt(0);
        switch (Q5)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
    
       JOptionPane.showMessageDialog(null,100 * Counter/5 + "% is what you got in relations ");
    }//GEN-LAST:event_relationsbtnActionPerformed

    private void NumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbersActionPerformed
        //Questions for Numbers
        Question  = JOptionPane.showInputDialog(null, "1. How many Bits does it take to represent an Octal number?\nA. 4\nB. 8\nC. 2\nD. 3\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Convert the following Decimal number 8 into a Binary\nA. 1000\nB. 00100\nC. 010101\nD. 0001\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. How many bits does it take to represent a Hexadecimal letter\nA. 8\nB. 2\nC. 4\nD. 22\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4.  Convert the following binary number 10 into a decimal number\nA. 1\nB. 22\nC. 10\nD. 2\nAnswer: ");
        char Q4=  Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        JOptionPane.showMessageDialog(null,100 * Counter/4 + "% is what you got in numbers ");
    }//GEN-LAST:event_NumbersActionPerformed

    private void MorenumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorenumbersActionPerformed
        //Questions for More numbers
        Question  = JOptionPane.showInputDialog(null, "1. Convert 1010 into a decimal number?\nA. 4\nB. 8\nC. 2\nD. 10\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Convert the following Decimal number 4 into a Binary\nA. 0100\nB. 00100\nC. 010101\nD. 0001\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. Covert 12 base 8 into a base 2 number\nA. 1100\nB. 0101\nC. 1010\nD. 1000\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4.  Convert A1 into a decimal number\nA. 161\nB. 22\nC. 148\nD. 97\nAnswer: ");
        char Q4 = Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question5  = JOptionPane.showInputDialog(null, "5. How many bits does it take to represent a Hexadecimal letter\nA. 8\nB. 2\nC. 4\nD. 22\nAnswer: ");
        char Q5 = Question5.charAt(0);
        switch (Q5)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        JOptionPane.showMessageDialog(null,100 * Counter/5 + "% is what you got in numbers ");
                                          

    }//GEN-LAST:event_MorenumbersActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        //Random question's
        Question  = JOptionPane.showInputDialog(null, "1. Convert 1010 into a decimal number?\nA. 4\nB. 8\nC. 2\nD. 10\nAnswer: ");
        char Q1 = Question.charAt(0);       
        switch (Q1)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question2  = JOptionPane.showInputDialog(null, "2. Convert the following Decimal number 8 into a Binary\nA. 1000\nB. 00100\nC. 010101\nD. 0001\nAnswer: ");
        char Q2 = Question2.charAt(0);
        switch (Q2)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
    }
        Question3  = JOptionPane.showInputDialog(null, "3. List the elements of the setP(A n B) given A={1,2} and B={2,3}\nA. {{},{2}}\nB. 0 a^^ N\nC. {-2,-1,0,1,2}\nD. 0 a^^R\nAnswer: ");
        char Q3 = Question3.charAt(0);
        switch (Q3)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        Question4 = JOptionPane.showInputDialog(null, "4.  Is the staement (P^(Q^T)))\nA. False\nB. Both\nC. True\nD. None\nAnswer: ");
        char Q4 = Question4.charAt(0);
        switch (Q4)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
    }
        Question5  = JOptionPane.showInputDialog(null, "5. Give the cardinality of the following set {}\nA. 2\nB. 0\nC. 10\nD. 1\nAnswer: ");
        char Q5 = Question5.charAt(0);
        switch (Q5)
            
    {
        case 'a': 
        case 'A':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'b':
        case 'B':
                    JOptionPane.showMessageDialog(null, "Correct! ");
                    Counter++;
                    break;
        case 'c': 
        case 'C':
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    break;
        case 'd':
        case 'D': 
                    JOptionPane.showMessageDialog(null, "Incorrect! ");
                    
                    break;
    }
        JOptionPane.showMessageDialog(null,100 * Counter/5 + "% is what you got in the random quiz");
    }//GEN-LAST:event_RandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsGUIpg3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Forlb;
    private javax.swing.JLabel Mathstitle;
    private javax.swing.JLabel Mathstitle1;
    private javax.swing.JButton Morenumbers;
    private javax.swing.JButton Numbers;
    private javax.swing.JButton Random;
    private javax.swing.JScrollPane Sites;
    private javax.swing.JTextArea Sitestf;
    private javax.swing.JLabel Testlb;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton logicbtn;
    private javax.swing.JButton relationsbtn;
    private javax.swing.JButton setbtn;
    private javax.swing.JPanel testpanel;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel titlelb;
    // End of variables declaration//GEN-END:variables
}
