/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsservice;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamie
 */
public class MathsGUIpg2 extends javax.swing.JFrame {

    private ArrayList<Maths> AppList;
    private String module, Description;
    private double Year;
    private int Number;
    private int count;

    public MathsGUIpg2() {
        initComponents();
        AppList = new ArrayList<>();
        module = new String();
        Description = new String();
        Number = 0;
        Year = 0;
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /*The ArrayList's used were studied from the tutroil videos
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelb = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Appoiment = new javax.swing.JPanel();
        Numberlb = new javax.swing.JLabel();
        Numbertf = new javax.swing.JTextField();
        yearlb = new javax.swing.JLabel();
        yeartf = new javax.swing.JTextField();
        Modulelb = new javax.swing.JLabel();
        subjecttf = new javax.swing.JTextField();
        Descriptionlb = new javax.swing.JLabel();
        description = new javax.swing.JScrollPane();
        descriptiontf = new javax.swing.JTextArea();
        Make = new javax.swing.JButton();
        View = new javax.swing.JButton();
        Stored = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Hints = new javax.swing.JScrollPane();
        Hintstf = new javax.swing.JTextArea();
        Hintstitle = new javax.swing.JLabel();
        Apptitlelb = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 725));
        getContentPane().setLayout(null);

        titlelb.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titlelb.setText("Maths Support Page");
        getContentPane().add(titlelb);
        titlelb.setBounds(140, 10, 190, 22);

        Back.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(10, 10, 100, 21);

        Next.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Next.setText("Next");
        Next.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(350, 10, 100, 21);

        Appoiment.setBackground(new java.awt.Color(204, 204, 204));
        Appoiment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Numberlb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Numberlb.setText("Student Number : ");

        Numbertf.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Numbertf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Numbertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbertfActionPerformed(evt);
            }
        });

        yearlb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        yearlb.setText("Year :");

        yeartf.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        yeartf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Modulelb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Modulelb.setText("Module :");

        subjecttf.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        subjecttf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Descriptionlb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Descriptionlb.setText("Description :");

        description.setHorizontalScrollBar(null);

        descriptiontf.setColumns(5);
        descriptiontf.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        descriptiontf.setRows(5);
        descriptiontf.setAutoscrolls(false);
        descriptiontf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        description.setViewportView(descriptiontf);

        Make.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Make.setText("Make an Appointment");
        Make.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Make.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeActionPerformed(evt);
            }
        });

        View.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        View.setText("View Active Appointments");
        View.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        View.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Stored.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Stored.setText("Stored Appointments");
        Stored.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Stored.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoredActionPerformed(evt);
            }
        });

        Deletebtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Deletebtn.setText("Delete Appointments");
        Deletebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppoimentLayout = new javax.swing.GroupLayout(Appoiment);
        Appoiment.setLayout(AppoimentLayout);
        AppoimentLayout.setHorizontalGroup(
            AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppoimentLayout.createSequentialGroup()
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppoimentLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AppoimentLayout.createSequentialGroup()
                                .addComponent(yearlb, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yeartf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AppoimentLayout.createSequentialGroup()
                                .addComponent(Modulelb, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subjecttf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AppoimentLayout.createSequentialGroup()
                                .addComponent(Descriptionlb, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AppoimentLayout.createSequentialGroup()
                                .addComponent(Numberlb, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numbertf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AppoimentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Make, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AppoimentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Stored, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        AppoimentLayout.setVerticalGroup(
            AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppoimentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numberlb)
                    .addComponent(Numbertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlb)
                    .addComponent(yeartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modulelb)
                    .addComponent(subjecttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descriptionlb)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Make)
                    .addComponent(View))
                .addGap(18, 18, 18)
                .addGroup(AppoimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stored)
                    .addComponent(Deletebtn))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        getContentPane().add(Appoiment);
        Appoiment.setBounds(10, 70, 440, 330);

        Hintstf.setColumns(20);
        Hintstf.setEditable(false);
        Hintstf.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Hintstf.setRows(5);
        Hintstf.setText("\nThe first and the biggest hint for studying for any Maths exam is to\ndo as many examples as possible.\n\nAnother good hint is to look at passed exam papers for your studying\n\nAttending the Maths sessions that the Maths support service puts on \nas they will go threw as many examples as possible \n\nAlways ask questions if you do not understand no questions are \nstupid and the lectures will have no problem going back over what \nthey have done.\n\n \n\n");
        Hintstf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Hints.setViewportView(Hintstf);

        getContentPane().add(Hints);
        Hints.setBounds(10, 420, 440, 250);

        Hintstitle.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Hintstitle.setText("Hints for Exams ");
        getContentPane().add(Hintstitle);
        Hintstitle.setBounds(180, 400, 140, 17);

        Apptitlelb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Apptitlelb.setText("Make an Appointment");
        getContentPane().add(Apptitlelb);
        Apptitlelb.setBounds(160, 50, 150, 17);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsservice/Images/Maths Background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 460, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        dispose();
        MathsGUIpg3 MGUI = new MathsGUIpg3();
        MGUI.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        MathsGUIpg1 MGUI = new MathsGUIpg1();
        MGUI.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void NumbertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumbertfActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        for (int i = 0; i < AppList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Student Number: " + AppList.get(i).getNumber() + "\n Year: " + AppList.get(i).getYear() + "\n Module: " + AppList.get(i).getmodule() + "\n Description: " + AppList.get(i).getDes());
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeActionPerformed
        //get text from textfields
        Number = Integer.parseInt(Numbertf.getText());
        Year = Double.parseDouble(yeartf.getText());
        module = subjecttf.getText();
        Description = descriptiontf.getText();

        Maths M = new Maths();
        M.setNumber(Number);
        M.setYear(Year);
        M.setmodule(module);
        M.setDes(Description);

        //add object to arraylist
        AppList.add(M);

        //increment counter
        count++;

        //File Handling
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        
        module = subjecttf.getText();
        Description = descriptiontf.getText();

        try {
            outFile = new File("Appointment.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(module);
            bw.newLine();
            bw.write(Description);
            bw.newLine();
            


            bw.close();
            JOptionPane.showMessageDialog(null, "Thanks for you submission ");
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }

        //clear feilds once entered
        Numbertf.setText("");
        yeartf.setText("");
        subjecttf.setText("");
        descriptiontf.setText("");
    }//GEN-LAST:event_MakeActionPerformed

    private void StoredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoredActionPerformed

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("Appointment.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            module = br.readLine();
            Description = br.readLine();
            while (module != null) {
                JOptionPane.showMessageDialog(null, "Module : " + module +"\nDescription : " + Description);
                module = br.readLine();
                Description = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_StoredActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        if(Numbertf.getText().equals("")||yeartf.getText().equals("")||subjecttf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter your Student Number, Year and the module to delete");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null,"Sorry, there are no items to delete at this time");
        }
        else{
        Number = Integer.parseInt(Numbertf.getText());
        Year = Double.parseDouble(yeartf.getText());
        module = subjecttf.getText();
            
            for(int i = 0; i < AppList.size();i++){
                if(AppList.get(i).getNumber()==Number&&AppList.get(i).getYear()==Year&&AppList.get(i).getmodule().equals(module)){
                    AppList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Your Appoinment has been deleted ");
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"Sorry, could not be found");
                }
            }
            //clear feilds once entered
        Numbertf.setText("");
        yeartf.setText("");
        subjecttf.setText("");
        }
    }//GEN-LAST:event_DeletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsGUIpg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsGUIpg2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appoiment;
    private javax.swing.JLabel Apptitlelb;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JLabel Descriptionlb;
    private javax.swing.JScrollPane Hints;
    private javax.swing.JTextArea Hintstf;
    private javax.swing.JLabel Hintstitle;
    private javax.swing.JButton Make;
    private javax.swing.JLabel Modulelb;
    private javax.swing.JButton Next;
    private javax.swing.JLabel Numberlb;
    private javax.swing.JTextField Numbertf;
    private javax.swing.JButton Stored;
    private javax.swing.JButton View;
    private javax.swing.JScrollPane description;
    private javax.swing.JTextArea descriptiontf;
    private javax.swing.JTextField subjecttf;
    private javax.swing.JLabel titlelb;
    private javax.swing.JLabel yearlb;
    private javax.swing.JTextField yeartf;
    // End of variables declaration//GEN-END:variables
}
