/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsservice;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamie
 */
public class QuestionGUI extends javax.swing.JFrame {

    private ArrayList<Question> QuestionList;
    private String name, email, service, Des;
    private int count;

    public QuestionGUI() {
        initComponents();
        QuestionList = new ArrayList<>();
        name = new String();
        email = new String();
        service = new String();
        Des = new String();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /*The ArrayList's used were studied from the tutroil videos
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionPanel = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        emaillb = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        servicetf = new javax.swing.JTextField();
        servicelb = new javax.swing.JLabel();
        deslb = new javax.swing.JLabel();
        des = new javax.swing.JScrollPane();
        destf = new javax.swing.JTextArea();
        submitbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        FAQbtn = new javax.swing.JButton();
        Searchbtn = new javax.swing.JToggleButton();
        Questionlogo = new javax.swing.JLabel();
        titlelb = new javax.swing.JLabel();
        Asklb = new javax.swing.JLabel();
        Homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(475, 725));
        getContentPane().setLayout(null);

        QuestionPanel.setBackground(new java.awt.Color(204, 204, 204));
        QuestionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        fullname.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fullname.setText("Full Name :");

        nametf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        emaillb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        emaillb.setText("Email : ");

        emailtf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        servicetf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        servicelb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        servicelb.setText("Service :");

        deslb.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        deslb.setText("Description :");

        destf.setColumns(20);
        destf.setRows(5);
        destf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        des.setViewportView(destf);

        submitbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        submitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        viewbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        viewbtn.setText("View Active Questions");
        viewbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        viewbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        FAQbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        FAQbtn.setText("Stored Questions");
        FAQbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        FAQbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FAQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAQbtnActionPerformed(evt);
            }
        });

        Searchbtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Searchbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuestionPanelLayout = new javax.swing.GroupLayout(QuestionPanel);
        QuestionPanel.setLayout(QuestionPanelLayout);
        QuestionPanelLayout.setHorizontalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionPanelLayout.createSequentialGroup()
                        .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(deslb)
                                .addGap(18, 18, 18)
                                .addComponent(des, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(servicelb)
                                .addGap(40, 40, 40)
                                .addComponent(servicetf))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(fullname)
                                .addGap(27, 27, 27)
                                .addComponent(nametf))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(emaillb)
                                .addGap(49, 49, 49)
                                .addComponent(emailtf)))
                        .addGap(27, 27, 27))
                    .addGroup(QuestionPanelLayout.createSequentialGroup()
                        .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FAQbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Searchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        QuestionPanelLayout.setVerticalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullname)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillb))
                .addGap(14, 14, 14)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicelb)
                    .addComponent(servicetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deslb)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbtn)
                    .addComponent(viewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAQbtn)
                    .addComponent(Searchbtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(QuestionPanel);
        QuestionPanel.setBounds(20, 60, 420, 320);

        Questionlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsservice/Images/Question1.png"))); // NOI18N
        getContentPane().add(Questionlogo);
        Questionlogo.setBounds(80, 390, 320, 310);

        titlelb.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titlelb.setText("Question's Page");
        getContentPane().add(titlelb);
        titlelb.setBounds(150, 10, 190, 22);

        Asklb.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Asklb.setText("Ask our different services Anything you want");
        getContentPane().add(Asklb);
        Asklb.setBounds(80, 40, 330, 17);

        Homebtn.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Homebtn.setText("Home");
        Homebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Homebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Homebtn);
        Homebtn.setBounds(10, 10, 100, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
        dispose();
        Homepage HGUI = new Homepage();
        HGUI.setVisible(true);
    }//GEN-LAST:event_HomebtnActionPerformed

    private void FAQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAQbtnActionPerformed
        //File Handling with Objects 
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("Q.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            /*Question x;
            x = (Question)oStream.readObject();*/
            ArrayList <Question> xList;
            xList = (ArrayList<Question>)oStream.readObject();
            for(Question x:xList){
            JOptionPane.showMessageDialog(null, "Name: "+x.getName()+"\nEmail: "+x.getEmail()+"\nService: "+x.getService()+"\nDescription: "+x.getDes());
            }
            
            oStream.close();
        }
        catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_FAQbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        for (int i = 0; i < QuestionList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Name: " + QuestionList.get(i).getName() + "\nEmail: " + QuestionList.get(i).getEmail() + "\nService: " + QuestionList.get(i).getService() + "\nDescription: " + QuestionList.get(i).getDes());
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        //get text from textfields
        name = nametf.getText();
        email = emailtf.getText();
        service = servicetf.getText();
        Des = destf.getText();

        Question Q = new Question();
        Q.setName(name);
        Q.setEmail(email);
        Q.setService(service);
        Q.setDes(Des);

        //add object to arraylist
        QuestionList.add(Q);

        //increment counter
        count++;

        //File Handling with Qbjects
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("Q.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(QuestionList);

            JOptionPane.showMessageDialog(null, "Question has been Submited and Stored");

            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }

        //clear feilds once entered
        nametf.setText("");
        emailtf.setText("");
        servicetf.setText("");
        destf.setText("");
    }//GEN-LAST:event_submitbtnActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        //Allows you to search by service and see the description of the problem
        String searchService = JOptionPane.showInputDialog(null, "Please enter the service you wish to search for");

        for (Question x : QuestionList) {
            if (searchService.equalsIgnoreCase(x.getService())) {
                JOptionPane.showMessageDialog(null, "Service: " + x.getService() + "\nDescription: " + x.getDes());
            }
        }
    }//GEN-LAST:event_SearchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new QuestionGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asklb;
    private javax.swing.JButton FAQbtn;
    private javax.swing.JButton Homebtn;
    private javax.swing.JPanel QuestionPanel;
    private javax.swing.JLabel Questionlogo;
    private javax.swing.JToggleButton Searchbtn;
    private javax.swing.JScrollPane des;
    private javax.swing.JLabel deslb;
    private javax.swing.JTextArea destf;
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel fullname;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel servicelb;
    private javax.swing.JTextField servicetf;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel titlelb;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
